import twilio from 'twilio';
import 'dotenv/config';
import express from 'express';
import crypto from 'node:crypto';
import admin from 'firebase-admin';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import {
  normalizePhone, recordMessage, loadMessages, loadConversationIndex,
  markConversationRead, rebuildConversationIndex, storageMode, firebaseStatus,
  getCarteraProSession, setCarteraProSession,
  loadCarteraProLeads, recordCarteraProLead,
  loadCarteraProOnboarding, getCarteraProOnboarding, saveCarteraProOnboarding,
  storeCarteraProUpload, getFirebaseStorageBucketName
} from './state.js';
import {
  handleCarteraProMessage, validateOnboardingToken, onboardingEncryptionReady,
  encryptCredentials, decryptCredentials
} from './carterapro_sales.js';

const __filename=fileURLToPath(import.meta.url);
const __dirname=path.dirname(__filename);
const app=express();
const PORT=Number(process.env.PORT||8080);
const UPLOAD_DIR=path.join(process.cwd(),'data','carterapro_uploads');
const UPLOAD_MAX_MB=Math.max(10,Math.min(Number(process.env.CARTERAPRO_UPLOAD_MAX_MB||100),250));
const DEMO_PDF_MAX_MB=Math.max(2,Math.min(Number(process.env.CARTERAPRO_DEMO_PDF_MAX_MB||12),25));
fs.mkdirSync(UPLOAD_DIR,{recursive:true});

process.on('unhandledRejection',err=>console.error('Promesa no manejada:',err?.message||err));
app.set('trust proxy',true);
app.use(express.json({limit:'15mb'}));
app.use(express.urlencoded({extended:true}));

function noCache(res){res.set({'Cache-Control':'no-store, no-cache, must-revalidate, proxy-revalidate','Pragma':'no-cache','Expires':'0','Surrogate-Control':'no-store'});}
function adminTokenExpected(){return process.env.ADMIN_TOKEN||process.env.MEDIA_ROUTE_TOKEN||'';}
function adminTokenFromReq(req){return req.headers['x-admin-token']||req.query.token||req.body?.token||'';}
function requireAdmin(req,res,next){const expected=adminTokenExpected();if(!expected)return next();if(String(adminTokenFromReq(req))===String(expected))return next();return res.status(401).json({ok:false,error:'Token de administrador inválido'});}
function adminPage(req,res){noCache(res);res.sendFile(path.join(__dirname,'..','public','carterapro-admin.html'));}
app.get(['/carterapro/admin','/carterapro-admin.html','/carterapro-inbox.html'],adminPage);
app.get('/carterapro-chat.html',(req,res)=>{const q=new URLSearchParams(); if(req.query.token)q.set('token',String(req.query.token)); if(req.query.phone)q.set('phone',String(req.query.phone));res.redirect(302,`/carterapro-admin.html?${q.toString()}`);});
app.get('/',(req,res)=>res.redirect(302,`/carterapro-admin.html${req.query.token?`?token=${encodeURIComponent(String(req.query.token))}`:''}`));
app.use(express.static(path.join(__dirname,'..','public')));

function requestBaseUrl(req){if(process.env.PUBLIC_BASE_URL)return String(process.env.PUBLIC_BASE_URL).replace(/\/$/,'');const proto=req.headers['x-forwarded-proto']||req.protocol||'https';const host=req.headers['x-forwarded-host']||req.headers.host;return `${proto}://${host}`.replace(/\/$/,'');}
function formatWhatsAppAddress(value){const raw=String(value||'').trim();if(!raw)return'';if(raw.startsWith('whatsapp:'))return raw;const clean=normalizePhone(raw);return clean?`whatsapp:+${clean}`:'';}
function twilioFromAddress(){return formatWhatsAppAddress(process.env.TWILIO_WHATSAPP_FROM||process.env.TWILIO_FROM||process.env.WHATSAPP_FROM||'');}
function adminNotifyNumbers(){return String(process.env.ADMIN_NOTIFY_NUMBERS||'5216622434983').split(',').map(normalizePhone).filter(Boolean);}
function twilioClient(){const sid=process.env.TWILIO_ACCOUNT_SID||'';const token=process.env.TWILIO_AUTH_TOKEN||'';if(!sid||!token)throw new Error('Faltan TWILIO_ACCOUNT_SID y/o TWILIO_AUTH_TOKEN');return twilio(sid,token);}
function directWhatsAppReplyLink(phone,text=''){let p=normalizePhone(phone);if(p.length===10)p=`52${p}`;return p?`https://wa.me/${p}${text?`?text=${encodeURIComponent(text)}`:''}`:'';}
function escHtml(value=''){return String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function xmlEscape(value){return String(value??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&apos;');}
function twimlMessage(reply={}){if(reply?.silent)return '<?xml version="1.0" encoding="UTF-8"?><Response></Response>';const body=reply?.body||'';return `<?xml version="1.0" encoding="UTF-8"?><Response>${body?`<Message><Body>${xmlEscape(body)}</Body></Message>`:''}</Response>`;}

async function sendAdminNotification(text){
  const from=twilioFromAddress(); if(!from)return {ok:false,error:'TWILIO_WHATSAPP_FROM no configurado'};
  const client=twilioClient(); const results=[];
  for(const phone of adminNotifyNumbers()){
    try{const sent=await client.messages.create({from,to:formatWhatsAppAddress(phone),body:String(text||'')});results.push({phone,ok:true,sid:sent.sid,status:sent.status});}
    catch(err){console.error('Aviso admin falló',phone,err?.code||'',err?.message||err);results.push({phone,ok:false,errorCode:err?.code||'',error:String(err?.message||err)});}
  }
  return {ok:results.some(x=>x.ok),results};
}
async function notifyCarteraProAdmin(text){try{return await sendAdminNotification(text)}catch(err){console.error('No se pudo avisar administración:',err?.message||err);return {ok:false,error:String(err?.message||err)}}}

function clickToWhatsAppReferral(body={}){const r={ctwaClid:String(body.ReferralCtwaClid||''),sourceId:String(body.ReferralSourceId||''),sourceType:String(body.ReferralSourceType||''),sourceUrl:String(body.ReferralSourceUrl||''),headline:String(body.ReferralHeadline||''),body:String(body.ReferralBody||''),mediaContentType:String(body.ReferralMediaContentType||'')};return Object.values(r).some(Boolean)?r:null;}

// ---------- Twilio log recovery: Twilio is backup, RTDB is the persistent inbox ----------
const twilioSyncState={lastRecentAtMs:0,lastRecentCount:0,lastStored:0,lastError:'',running:false};
function sameWhatsAddress(a,b){return normalizePhone(a)===normalizePhone(b);}
function twilioMessageOtherPhone(m){const ours=normalizePhone(twilioFromAddress()),from=normalizePhone(m?.from||''),to=normalizePhone(m?.to||'');if(from===ours)return to;if(to===ours)return from;return'';}
function twilioMessageDirection(m){return sameWhatsAddress(m?.from,twilioFromAddress())?'outbound':'inbound';}
async function persistTwilioLogMessage(m){
  const phone=twilioMessageOtherPhone(m);if(!phone||adminNotifyNumbers().includes(phone))return null;
  const direction=twilioMessageDirection(m);const createdAtMs=new Date(m?.dateCreated||m?.dateSent||Date.now()).getTime();
  const result=await recordMessage({phone,direction,source:'twilio_sync',body:String(m?.body||''),from:String(m?.from||''),to:String(m?.to||''),sid:String(m?.sid||''),status:String(m?.status||''),createdAt:m?.dateCreated||m?.dateSent||new Date(),createdAtMs});
  if(direction==='inbound'&&result&&!result.duplicate&&Date.now()-createdAtMs<15*60*1000)notifyInboundMessage({phone,body:String(m?.body||'')}).catch(()=>{});
  return result;
}
async function syncTwilioRecent({limit=500,force=false}={}){const now=Date.now();if(twilioSyncState.running)return {ok:true,skipped:true,...twilioSyncState};if(!force&&now-twilioSyncState.lastRecentAtMs<45000)return {ok:true,skipped:true,...twilioSyncState};twilioSyncState.running=true;try{const rows=await twilioClient().messages.list({limit:Math.max(20,Math.min(Number(limit||500),1000))});let stored=0;for(const m of rows){const r=await persistTwilioLogMessage(m);if(r&&!r.duplicate)stored++;}Object.assign(twilioSyncState,{lastRecentAtMs:Date.now(),lastRecentCount:rows.length,lastStored:stored,lastError:''});return {ok:true,fetched:rows.length,stored,...twilioSyncState};}catch(err){twilioSyncState.lastError=String(err?.message||err);console.error('Sync Twilio falló:',twilioSyncState.lastError);return {ok:false,error:twilioSyncState.lastError,...twilioSyncState};}finally{twilioSyncState.running=false;}}
async function syncTwilioPhone(phone,{limit=300}={}){const clean=normalizePhone(phone);if(!clean)return {ok:false,error:'Número inválido'};try{const addr=formatWhatsAppAddress(clean),each=Math.max(20,Math.min(Number(limit||300),500));const [toRows,fromRows]=await Promise.all([twilioClient().messages.list({to:addr,limit:each}),twilioClient().messages.list({from:addr,limit:each})]);const map=new Map();for(const m of [...toRows,...fromRows])map.set(m.sid,m);let stored=0;for(const m of map.values()){const r=await persistTwilioLogMessage(m);if(r&&!r.duplicate)stored++;}return {ok:true,fetched:map.size,stored};}catch(err){return {ok:false,error:String(err?.message||err)};}}

const inboundAlertBurst=new Map();
async function sendInboundAdminAlert(phone,preview,count=0){return notifyCarteraProAdmin([count?`🔔 *${count} mensajes nuevos en CarteraPro*`:'🔔 *Nuevo mensaje en CarteraPro*',`WhatsApp: ${phone}`,`Mensaje: ${preview}`,'',`📥 Panel: ${requestBaseUrlForLinks()}/carterapro-admin.html${adminTokenExpected()?`?token=${encodeURIComponent(adminTokenExpected())}`:''}`,`📲 Responder: ${directWhatsAppReplyLink(phone,'Hola, vi tu mensaje de CarteraPro. ¿En qué te puedo apoyar?')}`].join('\n'));}
function requestBaseUrlForLinks(){return String(process.env.PUBLIC_BASE_URL||'').replace(/\/$/,'');}
async function notifyInboundMessage({phone,body}){const clean=normalizePhone(phone);if(!clean||adminNotifyNumbers().includes(clean))return;const preview=String(body||'').trim().replace(/\s+/g,' ').slice(0,220)||'(mensaje sin texto)';const now=Date.now();let s=inboundAlertBurst.get(clean);if(!s||now-Number(s.lastAt||0)>90000){if(s?.timer)clearTimeout(s.timer);s={lastAt:now,pending:0,preview,timer:null};inboundAlertBurst.set(clean,s);await sendInboundAdminAlert(clean,preview,0);return;}s.pending++;s.preview=preview;if(s.timer)clearTimeout(s.timer);s.timer=setTimeout(async()=>{const x=inboundAlertBurst.get(clean);if(!x?.pending)return;const count=x.pending,last=x.preview;x.pending=0;x.lastAt=Date.now();x.timer=null;await sendInboundAdminAlert(clean,last,count);},45000);}

function latestByPhone(list=[]){const map=new Map();for(const item of list){const phone=normalizePhone(item.phone);if(!phone)continue;const t=Number(item.createdAtMs||new Date(item.createdAt||0).getTime()||0);const old=map.get(phone);const ot=old?Number(old.createdAtMs||new Date(old.createdAt||0).getTime()||0):-1;if(!old||t>=ot)map.set(phone,item);}return map;}
function salesStageFor(lead,onboarding){const os=String(onboarding?.status||'').toLowerCase();if(os==='files_received')return{key:'files_received',label:'ZIP recibido',priority:8};if(os==='credentials_received')return{key:'credentials_received',label:'Acceso recibido',priority:8};const type=String(lead?.type||'').toLowerCase(),status=String(lead?.status||'').toLowerCase();if(type==='registration'||status==='pending_activation')return{key:'registration',label:'Registro pendiente',priority:7};if(type==='purchase_reported'||status==='pending_verification')return{key:'purchase',label:'Pago reportado',priority:6};if(type.includes('onboarding')||status==='awaiting_documents')return{key:'onboarding',label:'Carga inicial',priority:5};if(type==='demo'||status==='demo_sent')return{key:'demo',label:'Demo enviada',priority:3};if(lead)return{key:'new',label:'Prospecto',priority:2};return{key:'message',label:'Mensaje WhatsApp',priority:1};}
async function buildInbox(){const [conversations,leads,onboarding]=await Promise.all([loadConversationIndex({limit:3000}),loadCarteraProLeads({limit:3000}),loadCarteraProOnboarding({limit:3000})]);const lm=latestByPhone(leads),om=latestByPhone(onboarding);return conversations.filter(c=>!adminNotifyNumbers().includes(normalizePhone(c.phone))).map(c=>{const phone=normalizePhone(c.phone),lead=lm.get(phone)||null,onboard=om.get(phone)||null;return {...c,area:'carterapro',name:lead?.name||onboard?.name||'',email:lead?.email||onboard?.email||'',company:lead?.company||onboard?.company||'',plan:lead?.plan||onboard?.plan||'',stage:salesStageFor(lead,onboard),leadType:lead?.type||'',leadStatus:lead?.status||'',onboardingMethod:onboard?.method||'',onboardingStatus:onboard?.status||'',onboardingToken:onboard?.token||''};}).sort((a,b)=>b.lastAtMs-a.lastAtMs);}

// ---------- API Admin unificada ----------
app.get('/health',async(req,res)=>{const fsx=firebaseStatus();res.json({ok:true,service:'CarteraPro only',provider:'twilio',storageMode:storageMode(),firebase:fsx,twilioFrom:normalizePhone(twilioFromAddress()),twilioSync:twilioSyncState});});
app.post('/api/admin/carterapro/sync-twilio',requireAdmin,async(req,res)=>{const phone=normalizePhone(req.body?.phone||req.query?.phone||'');const result=phone?await syncTwilioPhone(phone,{limit:Number(req.body?.limit||300)}):await syncTwilioRecent({limit:Number(req.body?.limit||800),force:true});res.status(result.ok===false?502:200).json(result);});
app.get('/api/admin/carterapro/inbox',requireAdmin,async(req,res)=>{await syncTwilioRecent({limit:650}).catch(()=>{});const conversations=await buildInbox();const unread=conversations.reduce((n,c)=>n+Number(c.unreadCount||0),0);res.json({ok:true,totals:{conversations:conversations.length,unread,ads:conversations.filter(c=>c.origin==='facebook_ads').length,closing:conversations.filter(c=>['purchase','registration','onboarding','credentials_received','files_received'].includes(c.stage?.key)).length},conversations,messageStorage:storageMode(),firebase:firebaseStatus(),twilioSync:twilioSyncState});});
app.get('/api/admin/carterapro/thread/:phone',requireAdmin,async(req,res)=>{const phone=normalizePhone(req.params.phone);await syncTwilioPhone(phone,{limit:450}).catch(()=>{});const requested=Math.max(20,Math.min(Number(req.query.limit||150),2000));const [messages,leads,onboarding,conversations]=await Promise.all([loadMessages({phone,limit:requested}),loadCarteraProLeads({limit:3000}),loadCarteraProOnboarding({limit:3000}),loadConversationIndex({limit:3000})]);const lead=latestByPhone(leads).get(phone)||null,onboard=latestByPhone(onboarding).get(phone)||null,conversation=conversations.find(x=>normalizePhone(x.phone)===phone)||null;await markConversationRead(phone).catch(()=>{});res.json({ok:true,phone,conversation,lead,onboarding:onboard,stage:salesStageFor(lead,onboard),messages:messages.slice().reverse()});});
app.post('/api/admin/carterapro/read/:phone',requireAdmin,async(req,res)=>res.json({ok:true,conversation:await markConversationRead(req.params.phone)}));
app.post('/api/admin/carterapro/rebuild-index',requireAdmin,async(req,res)=>{const c=await rebuildConversationIndex({limit:5000});res.json({ok:true,count:c.length});});
app.post('/api/admin/messages/reply',requireAdmin,async(req,res)=>{try{const phone=normalizePhone(req.body.phone),body=String(req.body.body||'').trim();if(!phone||!body)return res.status(400).json({ok:false,error:'Número o mensaje inválido'});const from=twilioFromAddress();if(!from)return res.status(400).json({ok:false,error:'TWILIO_WHATSAPP_FROM no configurado'});const sent=await twilioClient().messages.create({from,to:formatWhatsAppAddress(phone),body});const message=await recordMessage({phone,direction:'outbound',source:'manual',body,from,to:formatWhatsAppAddress(phone),sid:sent.sid||'',status:sent.status||'sent'});const current=await getCarteraProSession(phone).catch(()=>null);const until=new Date(Date.now()+Math.max(1,Number(process.env.CARTERAPRO_HUMAN_HANDOFF_HOURS||12))*3600000).toISOString();await setCarteraProSession(phone,{...(current||{createdAt:new Date().toISOString()}),state:'human_handoff',data:{...(current?.data||{}),humanHandoffUntil:until,humanHandoffReason:'respuesta_manual_admin',handoffNoticeSentAt:new Date().toISOString()}}).catch(()=>{});res.json({ok:true,message,twilio:{sid:sent.sid,status:sent.status}});}catch(err){res.status(500).json({ok:false,error:String(err?.message||err)});}});
app.get('/api/admin/carterapro/data',requireAdmin,async(req,res)=>{const [leads,onboarding]=await Promise.all([loadCarteraProLeads({limit:1000}),loadCarteraProOnboarding({limit:1000})]);res.json({ok:true,leads,onboarding,firebase:firebaseStatus(),storageMode:storageMode(),storageBucket:getFirebaseStorageBucketName()||'',twilioSync:twilioSyncState});});

// ---------- Demo WhatsApp ----------
app.get('/carterapro/demo-whatsapp',(req,res)=>{const target=adminNotifyNumbers()[0]||normalizePhone(twilioFromAddress());if(!target)return res.status(503).send('WhatsApp no configurado');const clean=(v,max=80)=>String(v||'').replace(/[\r\n<>]/g,' ').trim().slice(0,max);const client=clean(req.query.client)||'Cliente',vehicle=clean(req.query.vehicle)||'Kia Optima',model=clean(req.query.model)||'2013',date=clean(req.query.date)||'en los próximos días',company=clean(req.query.company)||'AXA';const message=[`Hola ${client} 👋`,'',`Le avisamos que la póliza de su ${vehicle} ${model} con ${company} está próxima a vencer ${date}.`,'','Estamos al pendiente para apoyarle con su renovación.','','— Mensaje de prueba de CarteraPro'].join('\n');res.redirect(302,directWhatsAppReplyLink(target,message));});

// ---------- Onboarding ----------
function buildOnboardingPage({title,subtitle,bodyHtml,error=''}){return `<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escHtml(title)}</title><style>*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,Segoe UI,Arial;background:#f5f7fb;color:#111827;padding:26px}.wrap{max-width:720px;margin:auto}.brand{font-weight:950;font-size:20px;margin:0 0 15px}.brand span{color:#4f6bff}.card{background:#fff;border:1px solid #e2e7f0;border-radius:22px;padding:24px}h1{font-size:27px;margin:0 0 7px}p{color:#697386;line-height:1.55}label{display:block;font-size:10px;font-weight:900;color:#697386;text-transform:uppercase;letter-spacing:.5px;margin:13px 0 5px}input{width:100%;border:1px solid #dce2eb;border-radius:11px;padding:11px;font:inherit}button{width:100%;margin-top:16px;border:0;border-radius:12px;min-height:47px;background:#4f6bff;color:#fff;font-weight:900}.note{background:#effbf6;border:1px solid #d3eee3;color:#176e55;padding:11px;border-radius:12px;font-size:11px}.warn{background:#fff5f6;border:1px solid #f0d7dc;color:#9b3043;padding:11px;border-radius:12px;font-size:11px}.small{font-size:10px;color:#8a93a3}</style></head><body><div class="wrap"><div class="brand">Cartera<span>Pro</span></div><div class="card"><h1>${escHtml(title)}</h1><p>${escHtml(subtitle)}</p>${error?`<div class="warn">${escHtml(error)}</div>`:''}${bodyHtml}</div></div></body></html>`;}
app.get('/carterapro/onboarding/acceso/:token',async(req,res)=>{const valid=await validateOnboardingToken(req.params.token,'portal');if(!valid.ok)return res.status(400).send(buildOnboardingPage({title:'Enlace no disponible',subtitle:'Solicita uno nuevo por WhatsApp.',bodyHtml:'',error:valid.reason}));const body=!onboardingEncryptionReady()?'<div class="warn">Falta configurar CARTERAPRO_ONBOARDING_SECRET en Render.</div>':`<div class="note"><b>Seguridad:</b> usa de preferencia una contraseña temporal.</div><form method="post"><label>Nombre</label><input name="name" required><label>Correo</label><input type="email" name="email" required><label>Compañía / portal</label><input name="company" required><label>URL portal</label><input name="portalUrl"><label>Usuario</label><input name="portalUser" required><label>Contraseña temporal</label><input type="password" name="portalPassword" required><label style="text-transform:none"><input type="checkbox" name="authorization" value="yes" required style="width:auto"> Autorizo el uso temporal para la carga inicial.</label><button>Enviar acceso seguro</button></form>`;res.type('html').send(buildOnboardingPage({title:'Carga inicial por portal',subtitle:'Proporciona acceso temporal para cargar tu cartera.',bodyHtml:body}));});
app.post('/carterapro/onboarding/acceso/:token',async(req,res)=>{const valid=await validateOnboardingToken(req.params.token,'portal');if(!valid.ok)return res.status(400).send(buildOnboardingPage({title:'Enlace no disponible',subtitle:'Solicita uno nuevo.',bodyHtml:'',error:valid.reason}));if(!onboardingEncryptionReady())return res.status(503).send('Cifrado no configurado');if(req.body.authorization!=='yes')return res.status(400).send('Falta autorización');const encrypted=encryptCredentials({portalUrl:String(req.body.portalUrl||'').trim(),portalUser:String(req.body.portalUser||'').trim(),portalPassword:String(req.body.portalPassword||'')});const updated=await saveCarteraProOnboarding({...valid.record,name:String(req.body.name||'').trim(),email:String(req.body.email||'').trim().toLowerCase(),company:String(req.body.company||'').trim(),credentialsEncrypted:encrypted,credentialsVersion:'aes-256-gcm-v1',status:'credentials_received',completedAt:new Date().toISOString()});await recordCarteraProLead({id:`onboarding_${updated.token}`,phone:updated.phone,name:updated.name,email:updated.email,company:updated.company,plan:updated.plan,type:'onboarding_portal',status:'received',note:'Credenciales cifradas recibidas'});notifyCarteraProAdmin(`🔐 Acceso temporal CarteraPro recibido\nCliente: ${updated.name||'-'}\nWhatsApp: ${updated.phone||'-'}\nCompañía: ${updated.company||'-'}`);res.type('html').send(buildOnboardingPage({title:'Acceso recibido',subtitle:'La información fue registrada de forma cifrada.',bodyHtml:'<div class="note"><b>Listo.</b> Ya podemos iniciar la carga.</div>'}));});
app.get('/carterapro/onboarding/zip/:token',async(req,res)=>{const valid=await validateOnboardingToken(req.params.token,'zip');if(!valid.ok)return res.status(400).send('Enlace no disponible');const body=`<div class="note">Sube un ZIP con los PDF de tus pólizas.</div><label>Nombre</label><input id="n"><label>Correo</label><input id="e" type="email"><label>Compañías</label><input id="c"><label>Archivo ZIP</label><input id="f" type="file" accept=".zip"><button onclick="up()">Subir cartera</button><div id="s" class="small"></div><script>async function up(){const f=document.getElementById('f').files[0];if(!f)return s.textContent='Selecciona un ZIP';s.textContent='Subiendo...';const r=await fetch(location.pathname,{method:'POST',headers:{'Content-Type':'application/zip','X-Cartera-File':encodeURIComponent(f.name),'X-Cartera-Name':encodeURIComponent(n.value),'X-Cartera-Email':encodeURIComponent(e.value),'X-Cartera-Company':encodeURIComponent(c.value)},body:f});document.open();document.write(await r.text());document.close();}</script>`;res.type('html').send(buildOnboardingPage({title:'Sube tu cartera',subtitle:`Máximo ${UPLOAD_MAX_MB} MB`,bodyHtml:body}));});
app.post('/carterapro/onboarding/zip/:token',express.raw({type:['application/zip','application/x-zip-compressed','application/octet-stream'],limit:`${UPLOAD_MAX_MB}mb`}),async(req,res)=>{const valid=await validateOnboardingToken(req.params.token,'zip');if(!valid.ok)return res.status(400).send('Enlace no disponible');if(!Buffer.isBuffer(req.body)||!req.body.length)return res.status(400).send('No se recibió ZIP');const dec=v=>{try{return decodeURIComponent(String(v||''))}catch{return String(v||'')}};const filename=dec(req.headers['x-cartera-file']||'cartera.zip').replace(/[\\/]/g,'_');const tmp=path.join(UPLOAD_DIR,`${Date.now()}_${crypto.randomBytes(5).toString('hex')}_${filename}`);fs.writeFileSync(tmp,req.body);const upload=await storeCarteraProUpload({token:valid.record.token,localPath:tmp,filename,contentType:'application/zip',size:req.body.length});const updated=await saveCarteraProOnboarding({...valid.record,name:dec(req.headers['x-cartera-name']).trim(),email:dec(req.headers['x-cartera-email']).trim().toLowerCase(),company:dec(req.headers['x-cartera-company']).trim(),upload,status:'files_received',completedAt:new Date().toISOString()});await recordCarteraProLead({id:`onboarding_${updated.token}`,phone:updated.phone,name:updated.name,email:updated.email,company:updated.company,plan:updated.plan,type:'onboarding_zip',status:'received',note:`ZIP recibido · ${upload.storedIn}`});notifyCarteraProAdmin(`📦 ZIP CarteraPro recibido\nCliente: ${updated.name||'-'}\nWhatsApp: ${updated.phone||'-'}\nArchivo: ${filename}`);res.type('html').send(buildOnboardingPage({title:'Archivo recibido',subtitle:'Tu cartera quedó registrada para carga inicial.',bodyHtml:'<div class="note"><b>Listo.</b> Te avisaremos por WhatsApp.</div>'}));});

// ---------- Netlify alerts ----------
function cors(req,res){const origin=String(req.headers.origin||'');const allowed=String(process.env.CARTERAPRO_ALLOWED_ORIGINS||'https://carteraproautos.netlify.app').split(',').map(x=>x.trim()).filter(Boolean);if(origin&&allowed.includes(origin))res.setHeader('Access-Control-Allow-Origin',origin);res.setHeader('Vary','Origin');res.setHeader('Access-Control-Allow-Methods','POST,OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, X-Cartera-Name, X-Cartera-Phone, X-Cartera-Email, X-Cartera-Company, X-Cartera-Missing, X-Cartera-File, X-Cartera-Source, X-Cartera-Username, X-Cartera-User-Uid');}
const hits=new Map();function rateLimit(req){const key=String(req.ip||'unknown'),now=Date.now(),arr=(hits.get(key)||[]).filter(x=>now-x<60000);if(arr.length>=20)return false;arr.push(now);hits.set(key,arr);return true;}
app.options(['/carterapro/api/registration-alert','/carterapro/api/demo-format-request'],(req,res)=>{cors(req,res);res.status(204).end();});
app.post('/carterapro/api/registration-alert',async(req,res)=>{cors(req,res);if(!rateLimit(req))return res.status(429).json({ok:false,error:'Demasiadas solicitudes'});const b=req.body||{},uid=String(b.uid||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,80),phone=normalizePhone(b.phone),name=String(b.name||'').trim().slice(0,120),email=String(b.email||'').trim().slice(0,160),plan=String(b.plan||'').toLowerCase()==='plus'?'plus':'basic',username=String(b.username||'').trim().slice(0,80),primaryCompany=String(b.primaryCompany||'').trim().slice(0,100),companies=Array.isArray(b.companies)?b.companies.map(x=>String(x).slice(0,80)).slice(0,20):[];if(!phone||phone.length<10||!name)return res.status(400).json({ok:false,error:'Datos incompletos'});await recordCarteraProLead({id:`registration_${uid||phone}`,phone,name,email,company:primaryCompany,plan,type:'registration',status:'pending_activation',note:`Usuario ${username||'-'} · Compañías: ${companies.join(', ')||'-'}`});notifyCarteraProAdmin(`✅ Nuevo registro CarteraPro\nNombre: ${name}\nWhatsApp: ${phone}\nPlan: ${plan}\nCompañía: ${primaryCompany||'-'}`);res.json({ok:true});});
app.post('/carterapro/api/demo-format-request',express.raw({type:['application/pdf','application/octet-stream'],limit:`${DEMO_PDF_MAX_MB}mb`}),async(req,res)=>{cors(req,res);if(!rateLimit(req))return res.status(429).json({ok:false,error:'Demasiadas solicitudes'});const dec=v=>{try{return decodeURIComponent(String(v||''))}catch{return String(v||'')}};const isPdf=Buffer.isBuffer(req.body),body=isPdf?{}:(req.body||{}),name=dec(req.headers['x-cartera-name']||body.name).trim().slice(0,120),phone=normalizePhone(dec(req.headers['x-cartera-phone']||body.phone)),email=dec(req.headers['x-cartera-email']||body.email).trim().toLowerCase().slice(0,180),company=dec(req.headers['x-cartera-company']||body.company).trim().slice(0,120),missing=dec(req.headers['x-cartera-missing']||(Array.isArray(body.missing)?body.missing.join(', '):body.missing)).trim().slice(0,400),original=dec(req.headers['x-cartera-file']||body.fileName||'poliza.pdf').replace(/[\\/]/g,'_').slice(0,140),source=String(req.headers['x-cartera-source']||body.source||'demo').toLowerCase()==='portal'?'portal':'demo',username=dec(req.headers['x-cartera-username']||body.username).trim().slice(0,80),uid=dec(req.headers['x-cartera-user-uid']||body.userUid).trim().slice(0,160);if(!name||!phone||phone.length<10)return res.status(400).json({ok:false,error:'Nombre y WhatsApp son obligatorios'});const token=`${source}format_${Date.now()}_${crypto.randomBytes(5).toString('hex')}`,method=source==='portal'?'portal_format':'demo_format';let upload=null;await saveCarteraProOnboarding({token,phone,name,email,company,method,status:'format_review',source,missingFields:missing,sourceUsername:username,sourceUserUid:uid,originalFileName:original,createdAt:new Date().toISOString()});if(isPdf&&req.body.length){const tmp=path.join(UPLOAD_DIR,`${Date.now()}_${crypto.randomBytes(5).toString('hex')}_${original.replace(/[^a-zA-Z0-9._-]+/g,'_')}`);fs.writeFileSync(tmp,req.body);upload=await storeCarteraProUpload({token,localPath:tmp,filename:original,contentType:'application/pdf',size:req.body.length});await saveCarteraProOnboarding({token,phone,name,email,company,method,status:'format_review',source,missingFields:missing,sourceUsername:username,sourceUserUid:uid,originalFileName:original,upload,completedAt:new Date().toISOString()});}await recordCarteraProLead({id:`${method}_${token}`,phone,name,email,company,type:method,source,status:'format_review',note:`Formato por adaptar · Faltan: ${missing||'-'} · PDF: ${upload?'sí':'no'}`});notifyCarteraProAdmin(`🧩 Formato CarteraPro por adaptar\nOrigen: ${source}\nNombre: ${name}\nWhatsApp: ${phone}\nCompañía: ${company||'-'}\nFaltan: ${missing||'-'}\nPDF: ${upload?'Sí':'No'}`);res.json({ok:true,requestId:token,fileReceived:Boolean(upload),storedIn:upload?.storedIn||''});});

app.get('/carterapro/admin/onboarding/:onboardingToken',requireAdmin,async(req,res)=>{const item=await getCarteraProOnboarding(req.params.onboardingToken);if(!item)return res.sendStatus(404);let creds=null,error='';if(item.credentialsEncrypted)try{creds=decryptCredentials(item.credentialsEncrypted)}catch(err){error=String(err?.message||err)}res.type('html').send(buildOnboardingPage({title:'Datos de carga inicial',subtitle:`${item.name||item.phone||''} · ${item.company||''}`,error,bodyHtml:creds?`<div class="warn"><b>Información sensible.</b></div><label>Portal</label><input readonly value="${escHtml(creds.portalUrl||'')}"><label>Usuario</label><input readonly value="${escHtml(creds.portalUser||'')}"><label>Contraseña temporal</label><input readonly value="${escHtml(creds.portalPassword||'')}">`:'<div class="note">No hay credenciales registradas.</div>'}));});
app.get('/carterapro/admin/file/:onboardingToken',requireAdmin,async(req,res)=>{const item=await getCarteraProOnboarding(req.params.onboardingToken),upload=item?.upload;if(!upload)return res.sendStatus(404);res.setHeader('Content-Disposition',`attachment; filename="${String(upload.filename||'archivo').replace(/"/g,'')}"`);res.setHeader('Content-Type',upload.contentType||'application/octet-stream');if(upload.storedIn==='firebase_storage'&&upload.storagePath&&getFirebaseStorageBucketName()){try{return admin.storage().bucket(getFirebaseStorageBucketName()).file(upload.storagePath).createReadStream().on('error',()=>res.sendStatus(404)).pipe(res)}catch{return res.sendStatus(500)}}const local=String(upload.localPath||''),resolved=path.resolve(local),root=path.resolve(UPLOAD_DIR)+path.sep;if(!local||!resolved.startsWith(root)||!fs.existsSync(resolved))return res.status(404).send('Archivo local ya no disponible. Configura FIREBASE_STORAGE_BUCKET.');res.sendFile(resolved);});

// ---------- Twilio webhook: SOLO CARTERAPRO ----------
app.post(['/twilio/webhook','/webhook'],async(req,res)=>{const incomingFrom=req.body.From||'',incomingTo=req.body.To||'',incomingBody=req.body.Body||'',sender=normalizePhone(incomingFrom),adContext=clickToWhatsAppReferral(req.body||{});try{
  // 1) Guardar SIEMPRE el mensaje entrante antes de intentar bot o aviso.
  await recordMessage({phone:sender,direction:'inbound',source:'carterapro_whatsapp',body:incomingBody,from:incomingFrom,to:incomingTo,sid:req.body.MessageSid||req.body.SmsMessageSid||'',status:req.body.SmsStatus||'',referral:adContext});
  // 2) El aviso al admin es secundario; si falla, el mensaje ya quedó en RTDB/inbox.
  notifyInboundMessage({phone:sender,body:incomingBody}).catch(()=>{});
  // 3) Todo mensaje se enruta únicamente a CarteraPro.
  const reply=await handleCarteraProMessage({from:incomingFrom,body:incomingBody,baseUrl:requestBaseUrl(req),notifyAdmin:notifyCarteraProAdmin,adContext});
  if(!reply?.silent&&reply?.body)await recordMessage({phone:sender,direction:'outbound',source:'carterapro_sales',body:reply.body,from:incomingTo,to:incomingFrom,status:'twiml'}).catch(()=>{});
  if(reply?.adminNotification)sendAdminNotification(reply.adminNotification).catch(()=>{});
  res.type('text/xml').send(twimlMessage(reply||{body:''}));
}catch(err){console.error('Webhook CarteraPro falló:',err);const fallback='Tuvimos un problema temporal. Tu mensaje ya quedó registrado y te atenderemos en cuanto sea posible.';await recordMessage({phone:sender,direction:'outbound',source:'carterapro_error',body:fallback,from:incomingTo,to:incomingFrom,status:'error'}).catch(()=>{});res.type('text/xml').send(twimlMessage({body:fallback}));}});

app.listen(PORT,()=>{console.log(`CarteraPro escuchando en http://localhost:${PORT}`);console.log('Modo: SOLO CARTERAPRO');console.log('Webhook: /twilio/webhook');setTimeout(()=>syncTwilioRecent({limit:1000,force:true}).catch(()=>{}),8000);const t=setInterval(()=>syncTwilioRecent({limit:500,force:true}).catch(()=>{}),60*1000);if(t.unref)t.unref();});
